
package monitorservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MonitorService", targetNamespace = "http://MonitorService", wsdlLocation = "file:/home/gordon/environment-monitor/environment-monitor/src-generated/MonitorService.wsdl")
public class MonitorService_Service
    extends Service
{

    private final static URL MONITORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(monitorservice.MonitorService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = monitorservice.MonitorService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/home/gordon/environment-monitor/environment-monitor/src-generated/MonitorService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/gordon/environment-monitor/environment-monitor/src-generated/MonitorService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MONITORSERVICE_WSDL_LOCATION = url;
    }

    public MonitorService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonitorService_Service() {
        super(MONITORSERVICE_WSDL_LOCATION, new QName("http://MonitorService", "MonitorService"));
    }

    /**
     * 
     * @return
     *     returns MonitorService
     */
    @WebEndpoint(name = "MonitorServicePort")
    public MonitorService getMonitorServicePort() {
        return super.getPort(new QName("http://MonitorService", "MonitorServicePort"), MonitorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonitorService
     */
    @WebEndpoint(name = "MonitorServicePort")
    public MonitorService getMonitorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://MonitorService", "MonitorServicePort"), MonitorService.class, features);
    }

}
